### ISSUE TITLE
Enabling module with default options prevents toggling tabs manually

### ISSUE THREAD

**Issue by andymce** [ekazyam/SidebarSeparator#14]
I've just spent quite a long time trying to figure this one out.

(See sublime forum for more details: https://forum.sublimetext.com/t/view-hide-tabs-doesnt-work/22975/15 ).

It seems that the "auto_tab_hide" setting prevents tabs from manually being shown and hidden (via Menu or Command Palette). 

I don't know this is the intended behaviour or not but it's very confusing. Consider not disabling manual control over tab visibility when this setting is enabled.

**Comment by ekazyam** [comment]
I'm sorry for the confusion.

This option is because I thought that it is inconvenient you see the long separator tab.
But as it can result in confusion, The options left, but set so as not to perform the control of the tab in the standard.

**Comment by andymce** [comment]
Thanks ekazyam that sounds like a good change.

Really the issue was that it was effecting all of my projects, even ones that didn't use the sidebar open files feature. In all sublime projects/workspaces the View/Hide/Toggle tab feature appeared to be broken. 

Is it possible that when "auto_hide_tab" is enabled, it just hides the tab without disabling View/Hide/Toggle tab altogether?

**Comment by ekazyam** [comment]
I think that's possible, but we believe that there is no meaning of auto_hide_tab options.

When set to true, it is because there is a possibility of confusion that any timing on whether to hide the tab, or to control whether to display.

The latest version of the state will consider the most simple.
true -> perform a complete control
false -> not control anything
